version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:07"
      timezone: UTC
    labels:
      - dependencies
      - go
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:17"
      timezone: UTC
    labels:
      - dependencies
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:27"
      timezone: UTC
    labels:
      - dependencies
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
